#!/bin/bash
LIBNAME=fd_lib
FDLIBVERSION=0.4.0
DESCRIPTION="A suite of externals and abstractions"
AUTHOR="Fede Camara Halac"
LICENSE="GPL -2+"
COMMONLIB=src/fdLib.c
EXTERNALS_FILE=doc/externals.pd
PDLIBBUILDER_DIR="pd-lib-builder"
README=README.txt
META=fd_lib-meta.pd
DATADIRS="doc data img scripts test examples"
# -----------------------------------------------------------------------------
#
# Load all sources
#
# -----------------------------------------------------------------------------
SOURCES=''
SOURCES_COUNT=0
for i in src/*.c; do
	if [[ "$i" != "$COMMONLIB" ]] && [[ "$i" != "src/$LIBNAME.c" ]]; then
		SOURCES+="$i "
		((SOURCES_COUNT++))
	fi
done
# -----------------------------------------------------------------------------
#
# Load all datafiles (abstractions, help files, texts)
#
# -----------------------------------------------------------------------------
DATAFILES=''
# store number of abstractions here for README.txt
DATAFILES_COUNT=0
# load abstractions
for i in abstractions/*.pd; do
	DATAFILES+="${i} "
	((DATAFILES_COUNT++))
done
# make sure readme and meta file are there
touch $README
touch $META
# continue loading help files and text files
for i in help/*.pd *.txt $META config.sh; do
	DATAFILES+="${i} "
done
# -----------------------------------------------------------------------------
#
# Check if pd-lib-dir exists here, otherwise make sure argument 1 has it
#
# -----------------------------------------------------------------------------
if [[ ! -d $PDLIBBUILDER_DIR ]]; then
	if [[ "$1" ]] && [[ -d "$1" ]] && [[ -f "$1/Makefile.pdlibbuilder" ]]; then
		PDLIBBUILDER_DIR="$1"
	else
		echo "Could not find '$PDLIBBUILDER_DIR'. Do you have pd-lib-builder?"
		echo "Pass the path to pd-lib-builder as argument 1 ..."
		echo "Or run the following:"
		echo "$ git submodule init"
		echo "$ git submodule update"
		exit 1
	fi
fi
# -----------------------------------------------------------------------------
#
# Load all objects
#
# -----------------------------------------------------------------------------
OBJECTS=''
DESCRIPTIONS=''
OBJECTS_COUNT=0
while IFS=$'\t' read -r -a obj; do
	OBJECTS[OBJECTS_COUNT]=${obj[0]}
	DESCRIPTIONS[OBJECTS_COUNT]=${obj[1]}
	((OBJECTS_COUNT++))
done <./objectlist.txt
# -----------------------------------------------------------------------------
#
# Make Makefile
#
# -----------------------------------------------------------------------------
echo "# Makefile for $LIBNAME version $FDLIBVERSION" >Makefile
echo "# Automatically generated by config.sh" >>Makefile
echo "lib.name=$LIBNAME" >>Makefile
# specify the location of main header file
echo "lib.setup.sources = src/\$(lib.name).c" >>Makefile
# all classes
echo "class.sources = $SOURCES" >>Makefile
# the common lib
echo "common.sources = $COMMONLIB" >>Makefile
# all abstractions, help files, and texts
echo "datafiles = $DATAFILES" >>Makefile
# all sub directories
echo "datadirs = $DATADIRS" >>Makefile
# standard c99 flag for linux
echo "define forLinux" >>Makefile
echo "    cflags += -std=c99" >>Makefile
echo "endef" >>Makefile
# build a multi-object library
echo "make-lib-executable=yes" >>Makefile
# provide the path to pd-lib-builder
echo "PDLIBBUILDER_DIR=$PDLIBBUILDER_DIR" >>Makefile
echo "include \$(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder" >>Makefile
# -----------------------------------------------------------------------------
#
# Make externals.pd
#
# -----------------------------------------------------------------------------
X=10
Y=20
echo "#N canvas 500 50 530 480 12;" >$EXTERNALS_FILE
echo "#X declare -lib $LIBNAME;" >>$EXTERNALS_FILE
echo "#X text 180 $Y $LIBNAME EXTERNALS;" >>$EXTERNALS_FILE
Y=$((Y + 30))
echo "#X obj 360 $Y declare -lib $LIBNAME;" >>$EXTERNALS_FILE
for i in $(seq 0 $((OBJECTS_COUNT - 1))); do
	echo "#X text $X $Y ${DESCRIPTIONS[i]};" >>$EXTERNALS_FILE
	echo "#X obj $X $((Y + 25)) ${OBJECTS[i]};" >>$EXTERNALS_FILE
	Y=$((Y + 60))
done
echo "#X text 200 $Y $LIBNAME version $FDLIBVERSION;" >>$EXTERNALS_FILE
echo "#X obj 250 $((Y + 40)) cnv 0 0 0 empty empty empty 0 0 0 0 0 0 0;" >>$EXTERNALS_FILE
# -----------------------------------------------------------------------------
#
# Make README.txt
#
# -----------------------------------------------------------------------------
echo "$LIBNAME" >$README
echo >>$README
echo "Current version: $FDLIBVERSION" >>$README
echo "$DESCRIPTION" >>$README
echo "Get Pure Data here: https://msp.ucsd.edu" >>$README
echo "It has:" >>$README
echo "    $DATAFILES_COUNT abstractions," >>$README
echo "    $SOURCES_COUNT externals," >>$README
echo "    shell scripts, and more." >>$README
echo "For an overview of the library open 'help/fd_lib-help.pd'" >>$README
echo "For instructions on how to compile see INSTALL.txt." >>$README
echo >>$README
echo "$LIBNAME is now available via \`deken\`, Pd's package manager." >>$README
echo "Open Pure Data and go to \`Help > Find Externals\`," >>$README
echo "then type \`$LIBNAME\` and download the binaries." >>$README
echo >>$README
echo "Use at your own risk and have fun!" >>$README
echo "fdch" >>$README
# -----------------------------------------------------------------------------
#
# Make fd_lib-meta.pd
#
# -----------------------------------------------------------------------------
echo "#N canvas 1 51 320 90 10;" >$META
echo "#N canvas 1 51 380 134 META 1;" >>$META
echo "#X text 10 10 NAME $LIBNAME;" >>$META
echo "#X text 10 30 VERSION $FDLIBVERSION;" >>$META
echo "#X text 10 40 DESCRIPTION $DESCRIPTION;" >>$META
echo "#X text 10 50 AUTHOR $AUTHOR;" >>$META
echo "#X text 10 90 LICENCE $LICENSE;" >>$META
echo "#X restore 43 36 pd META;" >>$META
echo "#X text 39 15 $LIBNAME: $DESCRIPTION;" >>$META
# -----------------------------------------------------------------------------
#
# Update version on header
#
# -----------------------------------------------------------------------------
perl -pi -e 's/(#define FDLIBVERSION).*/$1 "'"$FDLIBVERSION"'"/' ./src/fdLib.h
