name: package-lib
description: Package Pd library via deken

runs:
  using: "composite"
  steps:

    - name: Copy Library
      shell: bash
      run: |
        mkdir -p fd_lib/sources/pd-lib-builder
        cp fd_lib.* {.,abstractions,help}/*.pd fd_lib/
        cp -r examples doc data img scripts test fd_lib/
        cp Makefile *.{sh,txt} fd_lib/sources/
        cp src/*.{h,c} fd_lib/sources/
        cp pd-lib-builder/Makefile.pdlibbuilder fd_lib/sources/pd-lib-builder/

    - name: Compress Package
      shell: bash
      run: |
        tar -czf "$OUTPUT.tar.gz" ./fd_lib
    - name: upload artifacts
      uses: actions/upload-artifact@v5
      with:
        name: ${{ env.OUTPUT }}
        path: ${{ env.OUTPUT }}.tar


