name: package-lib
description: Package Pd library

inputs:
  output:
    description: "Output filename base"
    required: true

runs:
  using: "composite"
  steps:

    - name: Package The Library
      shell: bash
      run: bash scripts/package_lib.sh

    - name: Compress Package
      shell: bash
      run: |
        tar -czf "${{ inputs.output }}.tar.gz" ./fd_lib

    - name: Upload Artifacts
      uses: actions/upload-artifact@v5
      with:
        name: ${{ inputs.output }}
        path: ${{ inputs.output }}.tar.gz


