# Makefile for fd_lib

lib.name = fd_lib

class.sources = mainpath.c

datafiles = mainpath-help.pd README.txt LICENSE.txt

PDLIBBUILDER_DIR=~/Documents/dep/pd-lib-builder/
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder