name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get pdlibbuilder
      run: git submodule init && git submodule update
    - name: get pd
      run: | 
        git clone https://github.com/pure-data/pure-data.git
    - name: configure
      run: ./config.sh
    - name: make
      run: make PDINCLUDEDIR=./pure-data/src
    - name: install lib
      run: |
        make install PDLIBDIR=.
        zip -r fd_lib.zip ./fd_lib
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: make release
        path: ./fd_lib.zip
