name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get-pdlibbuilder
      run: git submodule init && git submodule update
    - name: get-pd
      run: sudo apt-get install pure-data pure-data-dev
    - name: configure
      run: ./config.sh
    - name: make
      run: make
