name: fd_lib-ci

on:
  push:
    branches: [ "main" ]

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    env:
      OUTPUT: fd_lib-ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: get pdlibbuilder
      run: git submodule init && git submodule update
    - name: get pd
      uses: actions/checkout@v2
      with:
        repository: pure-data/pure-data
        path: pure-data
    - name: configure
      run: ./config.sh
    - name: make
      run: make PDINCLUDEDIR=pure-data/src
    - name: install lib
      run: |
        make install PDLIBDIR=.
        zip -r "$OUTPUT.zip" ./fd_lib
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "$OUTPUT"
        path: "$OUTPUT.zip"


  macos-latest:
    runs-on: macos-latest
    env:
      OUTPUT: fd_lib-macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: get pdlibbuilder
      run: git submodule init && git submodule update
    - name: get pd
      uses: actions/checkout@v2
      with:
        repository: pure-data/pure-data
        path: pure-data
    - name: get dependencies
      run: |
        brew install automake autoconf libtool 
    - name: configure
      run: ./config.sh
    - name: make
      run: make PDINCLUDEDIR=pure-data/src
    - name: install lib
      run: |
        make install PDLIBDIR=.
        zip -r "$OUTPUT.zip" ./fd_lib
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "$OUTPUT"
        path: "$OUTPUT.zip"



  windows-latest:
    runs-on: windows-latest
    defaults:
        run:
          shell: bash
    env:
      OUTPUT: fd_lib-windows-latest
      PDVERSION: pd-0.53-2
    steps:
    - name: set environment variable
      run: echo "LOCAL_SHORT_COMMANDS=true" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: get pdlibbuilder
      run: git submodule init && git submodule update
    - name: get pd
      run: |
        curl -O "http://msp.ucsd.edu/Software/$PDVERSION.msw.zip"
        unzip "$PDVERSION.msw.zip"
    - name: configure
      run: ./config.sh
    - name: make
      run : make pdbinpath="$PDVERSION/bin" PDINCLUDEDIR="$PDVERSION/src" CFLAGS=-march=x86-64 -Iinclude
    - name: install lib
      run: |
        make install PDLIBDIR=.
        zip -r "$OUTPUT.zip" ./fd_lib
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "$OUTPUT"
        path: "$OUTPUT.zip"
